<?php
    $ticketRow = $this->ticketRow;
    echo '<h4 style="margin: 0 20px 5px 0;display:inline-block;">', 
            $this->escape($ticketRow['title']), 
         '</h4>';
    if ($ticketRow['status_id'] == 1) { // 1-pending, 2-close
        echo '待解决';
    } else {
        echo '已解决';
    }
?>
<pre><?php echo $this->escape($ticketRow['description']); ?></pre>
<div>
    <small>Customer: <?php echo $this->escape($ticketRow['customer']); ?> /</small>
    <small>Domain: <?php echo $this->escape($ticketRow['domain']); ?> /</small>
    <small><?php echo $ticketRow['time']; ?></small>
</div>