<?php

$userIsCustomer = false;
$userIsCustomerService = false;

$session = new Zend_Session_Namespace();
if (isset($session->customerId)) {
    $userIsCustomer = true;
} elseif (isset($session->customerServiceId)) {
    $userIsCustomerService = true;
} else {
    exit;
}
$ticketId = OurTicket_Util::DBAIPK(OurTicket_Util::getQuery('id'));
if (!$ticketId) {
    if ($userIsCustomer) {
        $this->redirect('/index/index?email=' . urlencode($session->customerEmail));
    } else {
        $this->redirect('/manage/index');
    }
    exit;
}

$db = Zend_Db_Table_Abstract::getDefaultAdapter();
if ($userIsCustomer) {
    $sql = "SELECT id FROM ticket WHERE id = $ticketId AND customer_id = " . $session->customerId;
    if (!$db->fetchOne($sql)) {
        $this->redirect('/index/index?email=' . urlencode($session->customerEmail));
        exit;
    }
}

if ($_POST) {
    try {
        OurTicket_Util::killCSRF();
        if ($userIsCustomer) {
            OurTicket_Ticket::customerAddComment(
                    $ticketId, OurTicket_Util::getPost('comment'), $session->customerId
            );
        } else {
            OurTicket_Ticket::customerServiceAddComment(
                    $ticketId, OurTicket_Util::getPost('comment'), $session->customerServiceId
            );
        }
    } catch (InvalidArgumentException $e) {
        exit('invalid params');
    } catch (Exception $e) {
        exit('Server error');
    }
}

if ($userIsCustomer) {
    $this->layout()->setLayout('layout');
} else {
    $this->layout()->setLayout('admin_layout');
}

$sql = "SELECT  ticket.*,
                    customer.email AS customer,
                    status.name AS status
            FROM    ticket
                    INNER JOIN customer ON ticket.customer_id = customer.id
                    INNER JOIN status ON ticket.status_id = status.id
            WHERE
                    ticket.id = $ticketId";
$ticketRow = $db->fetchRow($sql);

if ($userIsCustomer) {
    echo $this->partial('comment/ticket_info.phtml', array('ticketRow' => $ticketRow));
} else {
    echo $this->partial('comment/admin_ticket_info.phtml', array('ticketRow' => $ticketRow));
}
?>

<h3>Comments:</h3>
<?php
    $sql = "SELECT  content,
                    user_id,
                    user_type,
                    time
            FROM    comment
            WHERE
                    ticket_id = $ticketId 
                    ORDER BY id ASC";
    $commentRows = $db->fetchAll($sql);
    $customerServiceIds = array();
    foreach ($commentRows as $row) {
        if ($row['user_type'] == 2) { // 1-customer, 2-customer service
            $customerServiceIds[] = $row['user_id'];
        }
    }
    $customerServiceNames = array();
    if ($customerServiceIds) {
        $rows = $db->fetchAll('SELECT id, name FROM user WHERE id IN (' . implode(',', $customerServiceIds) . ')');
        foreach ($rows as $row) {
            $customerServiceNames[$row['id']] = $this->escape($row['name']);
        }
    }

    foreach ($commentRows as $row) {
        echo '<div class="row">';
        if ($row['user_type'] == 1) {
            if ($userIsCustomer) {
                echo '我';
            } else {
                echo $this->escape($ticketRow['customer']);
            }
        } else {
            echo $customerServiceNames[$row['user_id']];
        }
        echo '<pre>', $this->escape($row['content']), '</pre>';
        echo '<small>', $row['time'], '</small>';
        echo '</div>';
    }
?>

<h3>Add Comment:</h3>
<form method="POST">
    <textarea name="comment" rows="10" cols="80" placeholder="comment here..."></textarea>
    <br>
    <button type="submit">submit</button>
</form>


