<?php
    echo '<h4 style="margin: 0 20px 5px 0;display:inline-block;">', 
            $this->escape($this->ticketDetails['title']), 
         '</h4>';
    if ($this->ticketDetails['status_id'] == '1') { // 1-pending, 2-close
        echo '<a href="/index/close?id=', $this->ticketDetails['id'], '">Close</a>';
    } else {
        echo '<span>已解决</span>';
    }
?>
<pre><?php echo $this->escape($this->ticketDetails['description']); ?></pre>
<small><?php echo $this->ticketDetails['time']; ?></small>

<?php 
    echo $this->render('/index/ticket-comments.phtml'); 
    $this->commentFormAction = '/index/add-comment';
    echo $this->render('/index/comment-form.phtml');
?>
