<div class="container">
    <div class="mainbox">
        <?php if ($this->customerId): ?>
            <?php
            $ticketRows = array();
            if ($this->customerId) {
                $db = Zend_Db_Table_Abstract::getDefaultAdapter();
                $select = $db->select()
                             ->from('ticket', array('id', 'title'))
                             ->join('status', 'ticket.status_id = status.id', array('status' => 'status.name'))
                             ->where("customer_id = ".$this->customerId)
                             ->order(array('ticket.time DESC', 'ticket.id DESC'));
                $ticketRows = $db->fetchAll($select);
            }
            ?>
            <?php foreach ($ticketRows as $row): ?>
                <div class="row-title">
                    <div class="row-manage-title">
                        <a href="/ask/index?ticket=<?php echo $row['id']; ?>"> <?php echo $this->escape($row['title']); ?> </a>
                    </div>
                    <div class="row-manage-status">
                        <?php echo $row['status']; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            You have no ticket
        <?php endif; ?>

    </div>
</div>
