 <div class="mainbox">
    <?php
    $session = new Zend_Session_Namespace();
    $sql = 'SELECT  ticket.id,
                        ticket.title, 
                        status.name as status
                FROM    ticket 
                        INNER JOIN status ON ticket.status_id = status.id
                        WHERE ticket.customer_id = ? 
                        ORDER BY ticket.time DESC, ticket.id DESC';
    $rows = Zend_Db_Table_Abstract::getDefaultAdapter()->fetchAll($sql, array($session->customerId));
    foreach ($rows as $row) {
    ?>
        <div class="row">
            <a href="/comment/index?id=<?php echo $row['id']; ?>">
                <?php echo $this->escape($row['title']); ?>
            </a>
            <span class="status"><?php echo $row['status']; ?></span>
        </div>
    <?php } ?>
</div>
 