<div class="container">
    <div class="headbox">
        <div class="head-main-box">
            <div class="head-title">
                <p><h1>Ticket</h1>
                <p>customer: 
                    <?php
                        $session = new Zend_Session_Namespace();
                        echo $this->escape($session->customerEmail);
                    ?>
                </p>
            </div>
            <HR width="100%">
        </div>
    </div> 

    <div class="mainbox">
        <?php
            $ticketRows = array();
            if ($this->userId) {
                $db = Zend_Db_Table_Abstract::getDefaultAdapter();
                $select = $db->select()
                        ->from('ticket', array('id', 'title'))
                        ->joinInner('status', 'ticket.status = status.id', array('status' => 'status.name'))
                        ->where("user = $this->userId")
                        ->order(array('ticket.time DESC', 'ticket.id DESC'));
                $ticketRows = $db->fetchAll($select);
            }
        ?>
        <?php foreach ($ticketRows as $row): ?>
            <div class="row-title">
                <div class="row-manage-title">
                    <a href="/index.php/Ask/index?ticket=<?php echo $row['id']; ?>"> <?php echo $this->escape($row['title']); ?> </a>
                </div>
                <div class="row-manage-status">
                    <?php echo $row['status']; ?>
                </div>
            </div>
        <?php endforeach; ?>
        <?php
            if (!$this->userId) {
                echo 'You have no ticket';
            }
        ?>
    </div>
</div>