<h3>Comments:</h3>
<?php
    $sql = 'SELECT  content,
                    user_id,
                    user_type,
                    time
            FROM    comment
            WHERE
                    ticket_id = ' . $this->ticketDetails['id'] . '
                    ORDER BY id ASC';
    $db = Zend_Db_Table_Abstract::getDefaultAdapter();
    $commentRows = $db->fetchAll($sql);
    $customerServiceIds = array();
    foreach ($commentRows as $row) {
        if ($row['user_type'] == 2) { // 1-customer, 2-customer service
            $customerServiceIds[] = $row['user_id'];
        }
    }
    $customerServiceNames = array();
    if ($customerServiceIds) {
        $rows = $db->fetchAll('SELECT id, name FROM user WHERE id IN (' . implode(',', $customerServiceIds) . ')');
        foreach ($rows as $row) {
            $customerServiceNames[$row['id']] = $this->escape($row['name']);
        }
    }

    foreach ($commentRows as $row) {
        echo '<div class="row">';
        if ($row['user_type'] == 1) {
            if ($this->customerEmail) {
                echo $this->customerEmail;
            } else {
                echo '我';
            }
        } else {
            echo $customerServiceNames[$row['user_id']];
        }
        echo '<pre>', $this->escape($row['content']), '</pre>';
        echo '<small>', $row['time'], '</small>';
        echo '</div>';
    }
?>
