<?php
if (!isset($this->ticketId)) {
    exit('Missing required ticket');
}
?> 
<HR width="100%">
<div>comments:</div> 
<?php foreach ($this->paginator as $row): ?>
    <HR width="100%">
 
        <table>
            <tr>
                <th>user</th>
                <th>comment</th>
                <th>time</th>
            </tr>
            <tr>
                <td>
                    <?php
                    // user_type ( 1 = > table(`customer`) , 2 => table (`user`)             
                    if ($row['user_type'] == 1) {
                        $table = 'customer';
                    } else {
                        $table = 'user';
                    }
                    $db = Zend_Db_Table_Abstract::getDefaultAdapter();
                    $select = $db->select()->from($table, array('name'))->where("id = " . $row['user']);
                    $name = $db->fetchOne($select);
                    echo $this->escape($name);
                    ?>
                </td>
                <td><?php echo $this->escape($row['content']); ?></td>
                <td><?php echo $row['time']; ?></td>
            </tr>
        </table>
 
<?php endforeach; ?>

<p><?php echo $this->paginator; ?></p>