<?php
$ticketId = $this->ticketId;
if (!$ticketId) {
    $this->redirect('/index/index?email=' . urlencode($this->customerEmail));
    exit;
}

$db = Zend_Db_Table_Abstract::getDefaultAdapter();

$sql = "SELECT id FROM ticket WHERE id = $ticketId AND customer_id = " . $this->customerId;
if (!$db->fetchOne($sql)) {
    $this->redirect('/index/index?email=' . urlencode($this->customerEmail));
    exit;
}

$sql = "SELECT  ticket.*,
                    customer.email AS customer,
                    status.name AS status
            FROM    ticket
                    INNER JOIN customer ON ticket.customer_id = customer.id
                    INNER JOIN status ON ticket.status_id = status.id
            WHERE
                    ticket.id = $ticketId";
$ticketRow = $db->fetchRow($sql);

echo $this->partial('customer-comment/ticket_info.phtml', array('ticketRow' => $ticketRow));
?>

<h3>Comments:</h3>
<?php
$sql = "SELECT  content,
                    user_id,
                    user_type,
                    time
            FROM    comment
            WHERE
                    ticket_id = $ticketId 
                    ORDER BY id ASC";
$commentRows = $db->fetchAll($sql);
$customerServiceIds = array();
foreach ($commentRows as $row) {
    if ($row['user_type'] == 2) { // 1-customer, 2-customer service
        $customerServiceIds[] = $row['user_id'];
    }
}
$customerServiceNames = array();
if ($customerServiceIds) {
    $rows = $db->fetchAll('SELECT id, name FROM user WHERE id IN (' . implode(',', $customerServiceIds) . ')');
    foreach ($rows as $row) {
        $customerServiceNames[$row['id']] = $this->escape($row['name']);
    }
}

foreach ($commentRows as $row) {
    echo '<div class="row">';
    if ($row['user_type'] == 1) {
        echo '我';
    } else {
        echo $customerServiceNames[$row['user_id']];
    }
    echo '<pre>', $this->escape($row['content']), '</pre>';
    echo '<small>', $row['time'], '</small>';
    echo '</div>';
}
?>

<h3>Add Comment:</h3>
<form method="POST">
    <textarea name="comment" rows="10" cols="80" placeholder="comment here..."></textarea>
    <br>
    <button type="submit">submit</button>
</form>


