<form method="post">
    <?php
    if ($this->nameOrPwdWrong) {
        echo '<p style="color:red;padding-left:50px;">用户名或密码不对</p>';
    }
    ?>
    <div class="form-group col-md-8 column col-md-offset-2">
        <label for="name">user name:</label>
        <input type="text" class="form-control" name="name">
    </div>
    <div class="form-group col-md-8 column col-md-offset-2">
        <label for="password">password:</label>
        <input type="password" class="form-control" name="pwd">
    </div>
    <div class="form-group col-md-8 column col-md-offset-2">
    <button type="submit" class="btn btn-default">Submit</button>
    </div>
</form>