<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="/common/css/main.css">
</head>
<body>
    <div class="container">
        <div class="headbox">
            <h1>Ticket</h1>
            <p>
                user: 
                    <?php 
                        $session = new Zend_Session_Namespace();
                        echo $this->escape($session->customerServiceName); 
                    ?>
                /
                <a href="/logout/index">logout</a>
            </p>
        </div>
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>