<?php
    $session = new Zend_Session_Namespace();
    if (!isset($session->customerEmail)) {
        exit('this header need customerEmail');
    }
?>

<html>
<head>
<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="/common/css/main.css">
</head>
<body>
    <div class="container">
        <div class="headbox">
            <h1>Ticket</h1>
            <p>customer: <?php echo $this->escape($session->customerEmail); ?></p>
        </div>
        <?php echo $this->layout()->content; ?>
    </div>
</body>
</html>
