
<html> 
    <head>
        <meta charset="utf-8">
        <?php
        $this->headLink()->appendStylesheet('/common/css/main.css');
        echo $this->headLink();
        ?>
    </head>

    <body> 
        <div class="headbox">
            <div class="head-main-box">
                <div class="head-title">
                    <h1>Ticket</h1>
                    <p>user: 
                        <?php
                        $session = new Zend_Session_Namespace();
                        echo $this->escape($session->userName);
                        ?> / <a href="/manage/logout">logout</a>
                    </p>
                </div>
                <HR width="100%">
            </div>
        </div> 
        <div><?php echo $this->layout()->content ?></div> 
    </body>
</html>