<html> 
    <head>
        <meta charset="utf-8">
        <?php
            $this->headLink()->appendStylesheet('/common/css/main.css');
            echo $this->headLink();
        ?>
    </head>

    <body> 
        <div class="headbox">
            <div class="head-main-box">
                <div class="head-title">
                    <p><h1>Ticket</h1></p>
                    <p>
                        customer: 
                        <?php
                            $session = new Zend_Session_Namespace();
                            echo $this->escape($session->customerEmail);
                        ?>
                    </p>
                </div>
            </div>
        </div> 
        <div><?php echo $this->layout()->content ?></div> 
    </body>
</html>
