<?php
$ticketId = filter_var($_GET['ticket'], FILTER_VALIDATE_INT, array(
                'options' => array('min_range' => 1)
            ));
?>

<?php if ($this->pageCount): ?>
    <!-- First page link -->
    <?php if (isset($this->previous)): ?>
        <a href="<?php echo "?page=" . $this->first . "&ticket=" . $ticketId; ?>">
            First
        </a> |
    <?php else: ?>
        <span class="disabled">First</span> |
    <?php endif; ?>

    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
        <a href="<?php echo "?page=" . $this->previous . "&ticket=" . $ticketId; ?>">
            &lt; Previous
        </a> |
    <?php else: ?>
        <span class="disabled">&lt; Previous</span> |
    <?php endif; ?>

    <!-- Next page link -->
    <?php if (isset($this->next)): ?>
        <a href="<?php echo "?page=" . $this->next . "&ticket=" . $ticketId; ?>">
            Next &gt;
        </a> |
    <?php else: ?>
        <span class="disabled">Next &gt;</span> |
    <?php endif; ?>

    <!-- Last page link -->
    <?php if (isset($this->next)): ?>
        <a href="<?php echo "?page=" . $this->last . "&ticket=" . $ticketId; ?>">
            Last
        </a>
    <?php else: ?>
        <span class="disabled">Last</span>
    <?php endif; ?>

<?php endif; ?>
